// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "post": {
                "description": "Stores a single event with idempotency handling",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Create a new event",
                "parameters": [
                    {
                        "description": "Event payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fiber.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Duplicate event",
                        "schema": {
                            "$ref": "#/definitions/fiber.CreateEventResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/fiber.CreateEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_events_adapters_http_fiber.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_events_adapters_http_fiber.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/bulk": {
            "post": {
                "description": "Accepts a list of events and stores them individually",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Bulk create events",
                "parameters": [
                    {
                        "description": "Bulk event payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fiber.BulkCreateEventsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_events_adapters_http_fiber.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_events_adapters_http_fiber.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns metrics grouped by channel or time bucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Query aggregated metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event name",
                        "name": "event_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "From timestamp",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "To timestamp",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Group by: channel | time",
                        "name": "group_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Interval: minute | hour | day",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.MetricsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_metrics_adapters_http_fiber.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_metrics_adapters_http_fiber.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "fiber.BulkCreateEventsRequest": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/fiber.bulkEventItem"
                    }
                }
            }
        },
        "fiber.CreateEventRequest": {
            "description": "Event creation DTO",
            "type": "object",
            "properties": {
                "campaign_id": {
                    "type": "string"
                },
                "channel": {
                    "type": "string"
                },
                "event_name": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "fiber.CreateEventResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "fiber.MetricsGroupResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                },
                "unique_users": {
                    "type": "integer"
                }
            }
        },
        "fiber.MetricsResponse": {
            "type": "object",
            "properties": {
                "event_name": {
                    "type": "string"
                },
                "from": {
                    "type": "integer"
                },
                "group_by": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/fiber.MetricsGroupResponse"
                    }
                },
                "to": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "unique_users": {
                    "type": "integer"
                }
            }
        },
        "fiber.bulkEventItem": {
            "type": "object",
            "properties": {
                "campaign_id": {
                    "type": "string"
                },
                "channel": {
                    "type": "string"
                },
                "event_name": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_events_adapters_http_fiber.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid_event"
                },
                "message": {
                    "type": "string",
                    "example": "Event payload is invalid"
                }
            }
        },
        "internal_metrics_adapters_http_fiber.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid_event"
                },
                "message": {
                    "type": "string",
                    "example": "Event payload is invalid"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
